name: weeklymenu
description: "A Flutter application for managing custom recipes, generating weekly menus, and creating shopping lists."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  provider: ^6.1.5+1
  go_router: ^17.0.0
  cloud_firestore: ^6.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
